### ISSUE TITLE
USER STORY: Shop admin can create products

### ISSUE THREAD

**Issue by TolhurstTech** [TolhurstTech/petsy#11]
As a **Shop Admin** I can **add new products in the admin panel** so that **sell my products on my website**

## Acceptance Criteria:

- There is the ability to add a product to the website in the admin panel
- When the admin posts a new product it shows automatically on the home page
- The add product form contains fields for:
- [x] title
- [x] description
- [x] price
- [x] for sale/sold
- [x] draft
- [x] maybe shipping details
- [x] product image
- [x] category
- [x] date created
- [x] date updated
- [x] date published

## Tasks

- [ ] Task one
- [ ] Task two
- [ ] Task three
- [ ] Task four
- [ ] Task five
- [ ] \(Optional) This is an optional task
