### ISSUE TITLE
USER STORY: Navigate the website easily with a navbar

### ISSUE THREAD

**Issue by TolhurstTech** [TolhurstTech/petsy#3]
As a **customer** I can **find the most important parts of the website in an easy to use navbar** so that **I can navigate around the website swiftly from any page**

## Acceptance Criteria:

- I can find the main website pages in a simple, intuitive navbar
- The navbar is intuitive and displays what is most relevant depending on logged in or out site
- Navbar is responsive on different screen sizes and uses the expected burger logo on smaller screens

## Tasks

- [x] Create the navbar with semantic code
- [x] Create dynamic links for logged in and out users
- [x] Make sure links link to correct pages
- [x] The correct active page is selected for each page in the navbar
- [x] Aria labels are set correctly
- [x] Navbar is styled to the theme
