### ISSUE TITLE
USER STORY: User can login and logout

### ISSUE THREAD

**Issue by TolhurstTech** [TolhurstTech/petsy#9]
As a **customer** I can **login and logout of my account** so that **I can view my account and logout to keep my account safe**

## Acceptance Criteria:

- When logged out there is a clear login button
- When logged in there is a clear log out button
- When logging in the user is presented with a "you are now logged in" confirmation message
- The site shows a consistent logged status somewhere visible when a user is logged in
- When logging out the user is presented with a "You have successfully logged out" message

## Tasks

- [x] Install and wire allauth
- [x] Override signup to work with customer model
- [ ] Retheme template pages to match
- [ ] Task four
- [ ] Task five
- [ ] \(Optional) This is an optional task
